db-ui/core

source/css/_fonts.general.scss, source/css/db-ui-core.general.scss
Especially in DB UI Elements we'd like to consume the global declarations for fonts and more specifically declare those only to the scope of custom elements instead of `body, html` etc.
This change enables this exclusive consumption by extracting the declarations to another file.
=> refactor: splitted up those declarations for easier consumption

.github/scripts/publish-npm.sh
Removing the `dry-run` parameter from `npm publish` command within our CI/CD script.
=> refactor: let's release to npm

source/_patterns/02-components/accordion/accordion.scss
=> fix(accordion): replaced height by paddings

docs/getStarted.adoc, docs/migrationGuide.adoc
We could optimize the documentation on the necessary load path / include path within our documentation to lead the developers to the correct place (getting started).
=> docs: further documentation on the SCSS load path

source/_patterns/02-components/mainnavigation/_mainnavigation.variables.scss, source/_patterns/02-components/mainnavigation/mainnavigation.scss, source/_patterns/03-areas/00-header/_header.variables.scss
by header area and mainnavigation component
=> chore: aligned header background-colors

.github/actions/extract-branch/action.yml, .github/scripts/build-gh-page.sh, .github/workflows/00-scan-secrets.yml
from https://github.com/db-ui/elements/commit/d07fae26170427ed683828bbba146309de425dcb
=> refactor: adapted pipeline script parts

.github/scripts/build-gh-page.sh
Migrated too much stuff for the pipeline fix, resulting in that `deploy` doesn't work anymore.
=> fix(pipeline): deploy step

package.json
If a branch is being created for an issue through the GitHub UI, its branch name is starting with the issues number followed by the text. We should ensure that we even also support this within our branch name validation script.
=> refactor: correctly validate for default github created branch names

source/_patterns/01-elements/progress/progress.hbs, source/_patterns/01-elements/progress/progress.json, source/_patterns/01-elements/progress/progress.scss, source/_patterns/01-elements/progress/progress~circular-loader-dark-background.json, source/_patterns/01-elements/progress/progress~circular-loader.json, source/_patterns/01-elements/progress/progress~dark-background.json, source/_patterns/01-elements/progress/progress~linear-spinner-indeterminate.json, source/_patterns/01-elements/progress/progress~linear-spinner.json
Both inspired by [MDN technical documentation](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/progress) and further individual testing through the diverse audio description by JAWS, NVDA, iOS Voiceover and Microsoft Windows screen reader we've chosen a pattern that works best in all of those, after trying several other combinations and markup.
We're not making this a breaking change for the moment, as everybody should be able to do these changes in between.
=> refactor(progress): replaced output by label due to a11y testing

source/_patterns/00-base/type/_fonts.variables.scss
Added further font-faces:
- `DB Screen Head Regular` with a `font-weight` of `400`
- `DB Screen Sans Medium` with a `font-weight` of `500`
- `DB Screen Sans Semibold` with a `font-weight` of `600`
partly solves https://github.com/db-ui/core/issues/17
=> refactor: added further font faces

.markdown-lint.yml, package.json
Errors by `markdownlint` weren't shown on MacOS environments, but could get fixed by quoting the globs.
Fixes https://github.com/db-ui/core/issues/317
=> test(markdownlint): doesn't provide correct results

.github/workflows/00-init.yml, .github/workflows/00-scan-secrets.yml, .github/workflows/01-build.yml, .github/workflows/01-get-publish-version.yml, .github/workflows/01-lint.yml, .github/workflows/01-test.yml, .github/workflows/02-deploy-gh-pages.yml, .github/workflows/03-publish-packages.yml, .github/workflows/99-add-url-comment.yml, .github/workflows/99-auto-update-pr.yml, .github/workflows/99-codeql-analysis.yml, .github/workflows/99-dependency-review.yml, .github/workflows/cleanup.yml, source/_patterns/00-base/icons/_icons.helpers.scss, source/_patterns/00-base/icons/_icons.placeholder.scss
The `speak` property got a new value, so we're listing that one as well.
=> chore: icon font embedding optimization

.github/actions/npm-cache/action.yml, .github/workflows/00-init.yml, .github/workflows/00-scan-secrets.yml, .github/workflows/01-build.yml, .github/workflows/01-get-publish-version.yml, .github/workflows/01-lint.yml, .github/workflows/01-test.yml, .github/workflows/02-deploy-gh-pages.yml, .github/workflows/03-publish-packages.yml, .github/workflows/99-add-url-comment.yml, .github/workflows/99-auto-update-pr.yml, .github/workflows/99-codeql-analysis.yml, .github/workflows/99-dependency-review.yml, .github/workflows/cleanup.yml
Not using the same Node version leads to problems in the pipeline that weren't occuring on localhost, like e.g. the following in DB UI Elements repository: https://github.com/db-ui/elements/actions/runs/4220820918/jobs/7327485768
We're using the `init cache` action as the basis as this perfectly separates workflows / workflow steps that we even also run locally and the ones that are only run in the pipeline; great idea, thanks to @nmerget.
Fixes https://github.com/db-ui/core/issues/330
Even also needed to revert the previous version of this change that I've incorrectly provided with https://github.com/db-ui/core/pull/332 instead of this PR.
=> refactor: set pipelines and local node versions equally

source/_patterns/00-base/type/_fonts.variables.scss
to the stack of files that are possible to get referenced
=> refactor: added DB Screen Sans Digital Regular

source/css/pattern-scaffolding-project-specific.scss
Currently the vertical alignment of headline and products logo are off and need a slight adjustment on the intro page.
=> chore(intropage): simple headline/icon adjustment

source/_patterns/03-areas/00-header/header.scss
None of the child elements in header use floats, so the clearfix should be safely removable, fixing part of the problem in https://github.com/db-ui/elements/issues/1210
=> Remove clearfix from header

.github/workflows/01-test.yml
Resolves https://github.com/db-ui/core/issues/415
We're always depending on linting in combination with testing, so we could easily remove running the `lint` script within the `test` workflow:
- https://github.com/db-ui/core/blob/main/.github/workflows/release.yml#L36
- https://github.com/db-ui/core/blob/main/.github/workflows/default.yml#L46
- https://github.com/db-ui/core/blob/main/.github/workflows/default.yml#L51
This would speed up the test step by approx. 17 seconds.
=> fix: removed duplicated CI/CD activity

source/_patterns/01-elements/radio/radio.scss
Resolves https://github.com/db-ui/core/issues/428
=> fix(radio): thick border is only supposed to get used on checked state

source/_patterns/01-elements/buttons/button.scss
Resolves https://github.com/db-ui/core/issues/440
The `:active` pseudo-selector even also needs to get set in relation to `:disabled` state of the buttons.
=> fix(button): active disabled state visualization

source/_patterns/00-base/_init.scss
Resolves https://github.com/db-ui/core/issues/494
Introducing a CSS variable to still be able to overwrite the `box-sizing` value (which is the spirit of this whole thing), instead of e.g. "redeclaring" the following:
```css
details {
& > *,
& > ::before,
& > ::after {
box-sizing: border-box;
}
}
```
but doing the following instead:
https://github.com/db-ui/core/pull/495/files#diff-3c4b77e29eed06d8c4323c5b88e5e8bd3c78b0c2e077cda82f83eef04836614fR69-R77
more information on the problem:
https://kittygiraudel.com/2021/08/23/shadow-roots-and-inheritance/ & https://stackoverflow.com/questions/75347448/box-sizing-not-inherited-through-details-element
See also https://github.com/db-ui/mono/pull/1205
=> fix: incorrectly not inheriting values within `details` elements

source/_patterns/01-elements/input/_input.md, source/_patterns/01-elements/input/input.scss, source/_patterns/01-elements/input/input~auto-suggest.md
Resolve https://github.com/db-ui/core/issues/521
=> feat: enable a datalist example within our documentation

source/_patterns/02-components/accordion/_accordion.variables.scss, source/_patterns/02-components/accordion/accordion.scss
Resolves https://github.com/db-ui/core/issues/570
=> fix(accordion): arrow alignment

.lintstagedrc
Adding further file types to the lint staged config regarding xo testing: https://www.npmjs.com/package/xo#extensions
We don't need to enhance the list of filetypes for `xo`, as they are already included in the config (but not in documentation): https://github.com/xojs/xo/blob/37e14580c275a15fa36435d0cda7d45d3c515828/lib/constants.js#L24-L37
=> refactor(`lint staged`): added further `xo` supported filetypes

.lintstagedrc
We shouldn't run `html-validate` on staged `.hbs` files, as the `lint:html` would always mean a full build and testing on all resulting files.
=> fix: no `html-validate` on hbs filetypes

source/_patterns/01-elements/chips/chip.scss, source/_patterns/01-elements/chips/chips.json, source/_patterns/01-elements/tags/tag.scss, source/_patterns/01-elements/tags/tags.json
Resolves https://github.com/db-ui/core/issues/690
=> fix(chips & tags): missing default:light variant

source/_patterns/00-base/icons/_icons.helpers.scss
Due a bug within `summary` handling of pseudo elements with an alternative part defined by the simplification out of https://github.com/db-ui/core/pull/709 the icon within dropdown and overflow menu wouldn't get displayed currently.
=> fix(dropdown): icon not displaying on Safari

.github/actions/npm-cache/action.yml
Updated https://github.com/actions/setup-node to a new major version. Mainly the supported minimum Node version has been changed to Node 20.
=> chore: updated `actions/setup-node`

source/_patterns/01-elements/_form-elements.scss, source/_patterns/01-elements/input/input.hbs, source/_patterns/01-elements/input/input.scss, source/_patterns/01-elements/input/input~maxlength.json, source/_patterns/01-elements/input/input~maxlength.md, source/_patterns/01-elements/textarea/textarea.hbs, source/_patterns/01-elements/textarea/textarea.scss
Resolves https://github.com/db-ui/core/issues/811
=> refactor(input): added counter

source/_patterns/01-elements/buttons/10-button-width.hbs, source/_patterns/01-elements/buttons/_buttons.md, source/_patterns/01-elements/buttons/button.hbs, source/_patterns/01-elements/buttons/button.scss
resolves https://github.com/db-ui/core/issues/852
=> feat: providing auto width for buttons

source/_patterns/00-base/icons/_icons.helpers.scss, source/_patterns/01-elements/checkbox/checkbox.scss, source/_patterns/01-elements/select/select.scss, source/_patterns/01-elements/textarea/textarea.scss, source/_patterns/02-components/accordion/accordion.scss, source/_patterns/02-components/dialog/dialog.scss, source/_patterns/02-components/language-switcher/language-switcher.scss, source/_patterns/02-components/link-list/link-list.scss, source/_patterns/02-components/mainnavigation/mainnavigation.scss, source/_patterns/02-components/overflow-menu/overflow-menu.scss, source/_patterns/02-components/sitesearch/sitesearch.scss, source/_patterns/03-areas/00-header/meta.scss, source/_patterns/03-areas/03-footer/footer.scss
> Deprecation Warning: Sass's behavior for declarations that appear after nested
rules will be changing to match the behavior specified by CSS in an upcoming
version. To keep the existing behavior, move the declaration above the nested
rule. To opt into the new behavior, wrap the declaration in `& {}`.
> More info: https://sass-lang.com/d/mixed-decls
=> refactor: fix scss warnings

source/_patterns/01-elements/chips/_chip.hbs, source/_patterns/01-elements/chips/_chip.json, source/_patterns/01-elements/chips/chip.scss
Chips are composed of a `checkbox`/`radio` input and a label. As of now, the input is hidden entirely from screenreaders via `display: none` and the label has `role=button`, `aria-hidden=true` and is focusable via `tabindex=0`, though the latter is only true in the `core` examples, not in `db-ui/elements`*.
- In db-ui/elements, chips are not focusable at all! The input is hidden and the label is not focusable
- In db-ui/core, chip labels can be focused. But they can't be interacted with! They have role=button, but no keydown event handlers
- The labels (that act as buttons) have no explicit focus styles – though the user agent might automatically apply some (in Edge: a black outline)
- When a screenreader is active, interaction *can* work. Windows Narrator seems to dispatch `click` …
=> fix(chips): use built-in radiogroup / checkbox behavior for a11y

source/_patterns/02-components/accordion/accordion.scss
The `rem` unit is even already included within the SCSS variables, so we don't need to add it again via the `to-rem` SCSS function.
Resolves https://github.com/db-ui/core/issues/927
=> fix: duplicated rem units

source/_patterns/00-base/_helpers.scss, source/_patterns/00-base/_init.global.scss, source/_patterns/00-base/icons/_icons.font-faces.scss, source/_patterns/00-base/icons/_icons.helpers.scss, source/_patterns/00-base/icons/enterprise/_icons.variables.scss, source/_patterns/00-base/type/_fonts.scss, source/_patterns/01-elements/buttons/button.scss, source/_patterns/01-elements/loading-indicator/loading-indicator.scss
There were some deprecated code constructs that we needed to migrate to the new way of writing this code, like:
- color functions
- string functions
- `map-get` becomes `map.get`
=> refactor(sass): version migration

source/_patterns/02-components/table/table.scss, source/_patterns/02-components/table/table~sticky-header.md, source/_patterns/03-areas/_areas.scss
Resolves https://github.com/db-ui/core/issues/1052
=> fix: sticky table header depending on a sticky page header

.config/.lintstagedrc.json, .stylelintignore
In case that we're changing the stylelints configuration files content, we would need to validate it. And elsewhere we don't, compare to https://github.com/stylelint/stylelint/pull/8009
=> refactor(stylinelint): not lint config on every run

.config/.lintstagedrc.json
as the other linting / codestyle tools like `prettier` and `stylelint` are fixing the problems right away, we should active this as well for markdownlint.
=> refactor: aligned lint fixing
