db-ui/core

package-lock.json, package.json
Updated [`xo`](https://www.npmjs.com/package/xo) and overwritten one of its subdependency versions because of a security vulnerability being reported during installation.
=> refactor: updated xo and overwritten subdependency version

.env.template, .gitignore, .husky/pre-commit, .prettierrc.json, CONTRIBUTING.md, package-lock.json, package.json, scripts/check-commit-mail.js, scripts/check-commit-mail.mjs
We'd like to even also check for the correct commit email-address being used.
=> refactor: added pre-commit tests

.prettierrc.json
=> refactor: we'd mainly like to use the single quote for JS files

.github/scripts/package-version.sh, package-lock.json, package.json
As aligned a dependency that we're using within our CI/CD scripts needs to get added to `package.json` / our dependencies.
Similar to https://github.com/db-ui/base/pull/48
=> fix: added missing dependency to fix the release pipeline

.github/workflows/99-auto-merge.yml
inspired by https://github.com/dependabot/fetch-metadata/pull/246
=> refactor: not pinning CI/CD dependencies

package-lock.json, package.json
as this subdependency has been updated
=> chore: removed overwrite obsolete entry

.github/workflows/default.yml
We'd like to have a checks-done step within our pipeline that we could bind our success checks regarding merges to.
=> feat: add checks-done job

.github/workflows/default.yml
Follow up for https://github.com/db-ui/core/pull/103
=> chore: let's make checks done great again

source/_patterns/02-components/table/table.hbs
we obviously only need the condition around the table cell head element
=> chore: template simplification

.github/actions/extract-branch/action.yml
adapted from https://github.com/db-ui/base/pull/112
=> fix: issue deployment for releases and tags

tests/backstop.enterprise.json
Needed to replace some differentiated test cases by their grouping pages to decrease the testing time, as well as updated outdated URLs.
=> refactor(testing): housekeeping of backstopjs testcases / URLs

source/_patterns/01-elements/radio/radio.hbs, source/_patterns/01-elements/radio/radio~disabled-checked.json, source/_patterns/01-elements/radio/radio~disabled.json, source/_patterns/01-elements/radio/radio~invalid.json
Added invalid state to the documentation.
=> refactor(radio): show invalid state

source/_patterns/02-components/language-switcher/language-switcher.scss
Solves https://github.com/db-ui/elements/issues/493
=> fix(language-switcher): enhancing the possible languages

.stylelintrc.json
we need to find a better, logical ordering that we could agree on
=> refactor(stylelint): let's deactivate any ordering for now

source/_patterns/01-elements/radio/radio.hbs
=> chore: template optimization

docs/migrationGuide.adoc, source/_patterns/01-elements/progress/enterprise/_progress.demonstration.scss
Need to add this migrationGuide entry to the release within GitHub afterwards as well.
=> refactor(progress): made those necessary leftover changes

package-lock.json, package.json, source/_patterns/01-elements/checkbox/checkbox.scss, source/_patterns/01-elements/input/input.scss, source/_patterns/01-elements/radio/radio.scss, source/_patterns/01-elements/select/select.scss, source/_patterns/02-components/accordion/accordion.scss, source/_patterns/02-components/cards/card.scss, source/_patterns/02-components/table/_table.variables.scss
Updating DB UI Base as well as some of the changed variable names.
=> refactor: updated DB UI Base

source/_patterns/01-elements/logo/enterprise/logo.scss
Added missing file that we still need to render the enterprise components in DB UI Elements.
=> chore(logo): we still need this for enterprise component rendering

source/_patterns/01-elements/select/select-variations.hbs, source/_patterns/01-elements/select/select-variations~disabled.json, source/_patterns/01-elements/select/select.scss
=> fix: added missing select disabled styles

docs/getStarted.adoc
We've got some feedback regarding our getting started.
=> docs: updated getting started

source/_patterns/00-base/_init.global.scss
Resolves https://github.com/db-ui/core/issues/449
=> fix: we shouldn't use px on html tag at all

source/_patterns/03-areas/00-header/meta.hbs
Resolves https://github.com/db-ui/core/issues/487
=> fix(docs): reset incorrect footer items in metanavigation #487

source/_patterns/03-areas/00-header/header.scss
Resolves https://github.com/db-ui/core/issues/489
=> fix: mainnavigation placement in header w/o metanavigation

source/_patterns/00-base/icons/_icons.helpers.scss
=> refactor: enabled overwriting icons set via icon SCSS mixin

source/_patterns/00-base/type/_fonts.scss
Resolves https://github.com/db-ui/core/issues/557
=> refactor: added longest font name as well

.postcssrc, package-lock.json, package.json
Resolves https://github.com/db-ui/core/issues/589
=> feat: added PostCSS plugin cssnano

source/_patterns/00-base/icons/_icons.helpers.scss, source/_patterns/00-base/icons/_icons.placeholder.scss
Resolves https://github.com/db-ui/core/issues/598
=> refactor: (re)moved some leftovers out of #588

source/_patterns/00-base/icons/illustration-icons.json
Resolves https://github.com/db-ui/core/issues/615
=> docs(illustrative icons): corrected two icon names

enterprise.patternlab-config.json
Aligned keys and values in between `source` and `public` sections of the config.
Resolves https://github.com/db-ui/core/issues/643
=> fix: corrected configuration value

source/_patterns/00-base/icons/_icons.font-faces.scss, source/_patterns/00-base/icons/enterprise/_icons.font-faces.scss
Resolves https://github.com/db-ui/core/issues/653
=> refactor: updated icon fonts url

README.md, docs/adr/intro.adoc, source/_data/enterprise/footer.json, source/_patterns/01-elements/headline/_headline.md, source/_patterns/01-elements/logo/_logo.md, source/_patterns/04-pages/intro.json
some of the URLs within our [Marketingportal](https://marketingportal.extranet.deutschebahn.com/marketingportal) documentation have changed due to the release of version 3 the latest.
=> docs(marketingportal): updated urls

source/_patterns/00-base/icons/_icons.helpers.scss
we need to explain the solution.
=> docs: added relevant comment

source/_patterns/01-elements/_form-elements.scss, source/_patterns/01-elements/input/_input.md, source/_patterns/01-elements/input/input~invalid-attribute.md, source/_patterns/01-elements/radio/_radio.md, source/_patterns/01-elements/radio/radio.scss, source/_patterns/01-elements/select/_select.md, source/_patterns/01-elements/select/select~invalid-attribute.md, source/_patterns/01-elements/textarea/_textarea.md, source/_patterns/01-elements/textarea/textarea~invalid-attribute.md, source/_patterns/02-components/form/_form.md
Partly resolves https://github.com/db-ui/core/issues/933
=> refactor: using :user-*valid from now on

source/_patterns/02-components/breadcrumb/breadcrumb.scss
resolves https://github.com/db-ui/core/issues/941
=> fix(breadcrumb): different font-sizes

source/_patterns/02-components/metanavigation/metanavigation.scss
Resolves https://github.com/db-ui/core/issues/949
=> fix(metanavigation): unexpectedly hiding metanavigation items in footer

source/_patterns/01-elements/_form-elements.scss
Resolves https://github.com/db-ui/core/issues/981
=> refactor: replace renamed CSS property

package-lock.json, package.json
as we've updated `validate-branch-name`
=> refactor: removed obsolete overrite

.pa11yci, package.json
This reverts commit b8fab3219aed99257ac54f776019689e955abbe1.
=> Revert "fix(pa11y): conditions (#1079)"

source/_patterns/02-components/table/_table.helpers.scss
Relates to https://github.com/db-ui/core/issues/1052 and resolves https://github.com/db-ui/core/issues/779
=> refactor(table): only set backdrop-filter once
